### ISSUE TITLE
CSS Macro not working

### ISSUE THREAD

**Issue by Andriow** [Valassis-Digital-Media/nbconflux#15]
Hi, i am trying to use nbconflux, but i am not able to enable the CSS Macro, could you add some step by step to enable this feature, or add some link to this in the documentation, please? I am using confluence server here.

**Comment by parente** [comment]
@Andriow Sorry, but I do not know the steps to enable the CSS macro. The admin(s) of our Confluence instance turned it on and I don't have that level of access to poke around.

**Comment by danizen** [comment]
@Andriow , I had this issue and got past it.   If you are the administrator of the space, you can add the needed styles within the space stylesheet.  I went there as follows:

* Space Tools
* Look and Feel
* Stylesheet
* Edit

Then, paste this in:

```css
@import "https://nbviewer.jupyter.org/static/build/notebook.css";

a.anchor-link {
    display: none !important;
}
body div.output_subarea {
    max-width: none;
}
body.page-gadget #main {
    width: auto;
}
body.page-gadget {
    padding-top: 0;
}
```
